### PR TITLE
rewrite it in nushell

### PR DESCRIPTION
**Pull request by amtoine**
hey there :wave: :yum: 

i saw this on the Discord of Zellij and thought it was quite cool :sparkles: 

i had some fun rewriting it in Nushell, so here it is :smirk: 

> **Note**
> don't feel forced to land this, i mostly wanted to share this other way of writing the same script with ya :relieved: 

the [README](https://github.com/amtoine/zellij-sessionizer/tree/rewrite-the-script-in-nushell#zellij-sessionizer) now includes a section about the Nushell version of the sessionizer :+1:

### CODE REVIEW

**Comment by silicakes** [comment]
Love it!
The only thing I wanna solve is the ergonomics for specifying a path on my end.
I'll specify it the way you did - with using a variable and just switch the shortcut to include it - once it's done, we can merge yours too!

**Comment by amtoine** [comment]
> Love it! 
>
oooh nice, i'm glad you like it :blush: 

> The only thing I wanna solve is the ergonomics for specifying a path on my end. I'll specify it the way you did - with using a variable and just switch the shortcut to include it
>
it's been a looooong time i've not written any Bash so i'll trust you on this one :wink: :relieved: 

> once it's done, we can merge yours too!
>
amazing, can't wait :star_struck:

**Comment by amtoine** [comment]
i've been able to enable it as a binding in Nushell with
```bash
    {
        name: zellij_sessionizer
        modifier: control
        keycode: char_f
        mode: [emacs, vi_insert, vi_normal]
        event: {
            send: executehostcommand
            cmd: "zellij-sessionizer.nu $env.GIT_REPOS_HOME"
        }
    }
```

however, the limitation of 2 depth level in the script makes it not super easy to jump to any project :thinking: 

i've got a bunch of ideas but i need to try out the script a little more :smirk: 
i might come back a bit later, you'll have plenty of time to fix your end i think :relieved:

**Comment by silicakes** [comment]
> i've been able to enable it as a binding in Nushell with
> 
> ```shell
>     {
>         name: zellij_sessionizer
>         modifier: control
>         keycode: char_f
>         mode: [emacs, vi_insert, vi_normal]
>         event: {
>             send: executehostcommand
>             cmd: "zellij-sessionizer.nu $env.GIT_REPOS_HOME"
>         }
>     }
> ```
> 
> however, the limitation of 2 depth level in the script makes it not super easy to jump to any project 🤔
> 
> i've got a bunch of ideas but i need to try out the script a little more 😏 i might come back a bit later, you'll have plenty of time to fix your end i think 😌

Done and merged this:

https://github.com/silicakes/zellij-sessionizer/pull/3

Will you be able to update the readme so that people know it supports nushell now?
Feel free to include your example (the readme has one for sh/zsh).

As for the depth part - *lets talk about it*.
Perhaps we'll need to support some kind of arg passing i.e `zellij-sessionizer --depth ... --paths..` or perhaps setting up some global variables instead, like:

```sh
ZELLIJ_SESSIONIZER_PATHS=...
ZELLIJ_SESSIONIZER_SEARCH_DEPTH=...
```

But this will be outside the scope of this PR, so we can merge it regardless!

**Comment by amtoine** [comment]
> Done and merged this:
> https://github.com/silicakes/zellij-sessionizer/pull/3
>
noice, that's better for sure not to require users to change the source manually :ok_hand: 

> Will you be able to update the readme so that people know it supports nushell now?
> Feel free to include your example (the readme has one for sh/zsh).
> 
i can do that for sure!
in progress... :recycle:

**Comment by amtoine** [comment]
a new section about Nushell has been added in the [README](https://github.com/amtoine/zellij-sessionizer/tree/rewrite-the-script-in-nushell#zellij-sessionizer) :relieved:

**Comment by amtoine** [comment]
yeah, sorry about the back and forth but i forgot two super important part of the script :open_mouth:
- a bit of help to have a nice `zellij-sessionizer.nu --help` page
- an early return in the case the user does not choose anything with `fzf`

**Comment by silicakes** [comment]
> yeah, sorry about the back and forth but i forgot two super important part of the script 😮
> 
> * a bit of help to have a nice `zellij-sessionizer.nu --help` page
> * an early return in the case the user does not choose anything with `fzf`

 Huh, It seems like I also accidentally deleted mine. Will restore it in a [new PR](https://github.com/silicakes/zellij-sessionizer/pull/5).
 As for the `--help` part, lets get an issue for it too!
 
 Meanwhile, approving this one.
 Great job!

**Review by silicakes — APPROVED** [review]

**Comment by amtoine** [comment]
> Huh, It seems like I also accidentally deleted mine. Will restore it in a [new PR](https://github.com/silicakes/zellij-sessionizer/pull/5). As for the `--help` part, lets get an issue for it too! 
>
yeah i think it's important to have these :yum: 

> Meanwhile, approving this one. Great job!
>
yeah :partying_face: 
thanks for the review, feel free to land this anytime :relieved:

**Pull request merged**
